### ISSUE TITLE
Use IndiePaas images as a base

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/applications#49]
We can leave the IndiePaas images where they are https://registry.hub.docker.com/search?q=indiepaas and then add in a mysql server and a /snapshot.sh script where desired/necessary. This is maybe easier than the git submodule approach we tried last week.

@pierreozoux do you agree with this approach?

**Comment by pierreozoux** [comment]
I think in fact it is easier.

I didnt merge because this change had a lot of impact :
 - no docker hub build - due to submodule not supported
 - different instructions to install
 - make sure everything is working as expected

And didn't have this amount of time.

I agree on the approach, and then, I 'll migrate them one by one. You can close the issue if you want.

(As already said, I'll have more time in June to work on these matters)

**Comment by michielbdejong** [comment]
I thought of an even easier solution: tell IndiePaas to pull `indiehosters/<image>` instead of `indiepaas/<image>` from the hub, and then remove the dockerfiles folder from indiepaas altogether.
